spring:
  application:
    name: messaging-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/messaging_service
  cloud:
    function:
      definition: userRegistrationDownstreamConsumer;messageEventDownstream; messageMentionedNotificationDownstream; messageReactedNotificationDownstream
    Stream:
      bindings:
        userRegistrationDownstreamConsumer-in-0:
          destination: topic.user.registration
        messageEventDownstream-out-0:
          destination: topic.message.events
        messageMentionedNotificationDownstream-out-0:
          destination: topic.notification.trigger.message.mentioned
        messageReactedNotificationDownstream-out-0:
          destination: topic.notification.trigger.message.reacted
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true