spring:
  application:
    name: messaging-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/messaging_service

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true